# Import libraries
import dash
from dash import dcc
from dash import html
import dash_bootstrap_components as dbc
import string
import statistics
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import psutil
import random
import math
import csv
import sys
from h2o.automl import H2OAutoML
import h2o
from pathlib import Path
from dash.dependencies import Input, Output, State
from configparser import ConfigParser


# Load config.ini file
config = ConfigParser(allow_no_value=True)
config.read('config.ini')

my_threads = int(config['DEFAULT']['my_threads'])
my_max_ram_allowed = int(config['DEFAULT']['my_max_ram_allowed'])

# If you are assigning callbacks to components that are
# generated by other callbacks (and therefore not in the
# initial layout), you can suppress this exception by setting
# `suppress_callback_exceptions=True`.
suppress_callback_exceptions = True

# -------------------------------
# Random key generator - function
# -------------------------------
def random_key_generator(size=6, chars=string.ascii_letters + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))


# get current directory (PosixPath)
# -----------------------
my_current_dir = Path.cwd()

# check runtime mode - either many servers on the machine (server_multicore = F)
# or one server per one machine (server_multicore = T)
# -------------------------------------------
my_cores = my_threads

# check system free mem and apply it to the server
# ------------------------------------------------
memfree = psutil.virtual_memory().total
memfree_g = int(round(memfree / 1024 / 1024 / 1024 / my_cores))

if memfree_g < 2:
    memfree_g = 2

# Create three random strings
# -------------------------
aml_name = 'A' + random_key_generator(15)  # for FS project name
aml2_name = 'A' + random_key_generator(15)  # for classic approach project name
cluster_name = 'A' + random_key_generator(15)  # for h2o cluster name

# -------------------------------------
# run h2o server
# -------------------------------------
h2o.init(nthreads=my_threads,
         min_mem_size=memfree_g,
         max_mem_size=memfree_g,
         port=57750,
         ip='127.0.0.1',
         #         ice_root=str(my_export_dir),
         name=str(cluster_name),
         start_h2o=True)
# -------------------------------------

# --------------------------------------
# Load h2o model
# --------------------------------------
my_model = h2o.load_model('model/DeepLearning_grid__2_AutoML_20210831_185216_model_20')

# --------------------------------------
# Load test data
# --------------------------------------
my_data = pd.read_csv('data/ODT_Disintegration_Time_db_expanded_raw_v17_1.csv', sep='\t', index_col=0)

extracted_column_names = ["API_perc", "Mannitol_perc",	"MCC_perc",	"Lactose_perc",	"Calcium_silicate_perc",
                          "HPMC_perc",	"Sodium_bicarbonate_perc",	"SSG_perc",	"CC_Na_perc",
                          "Crospovidone_perc",	"L_HPC_perc",	"Pregelatinized_starch_perc",
                          "Sodium_carboxymethyl_starch_perc",	"Mg_stearate_perc",	"Aerosil_perc",
                          "Sodium_stearyl_fumarate_perc",	"Colloidal_silicon_dioxide_perc",	"Talc_perc",
                          "X2HP_bCD_perc",	"bCD_perc",	"CD_methacrylate_perc",	"Amberlite_IRP_64_69_perc",
                          "Eudragit_EPO_perc",	"Poloxamer_188_perc",	"PVP_perc",	"SLS_perc",	"PVA_perc",
                          "Camphor_perc",	"Hardness_N",	"GATS7i",	"Thickness_mm",	"GGI7",	"MATS4p",
                          "MIC2",	"Punch_mm",	"nT12Ring",	"XLogP",	"GATS7p",	"nF8HeteroRing",
                          "Disintegration_time_sec"]
my_data = my_data[extracted_column_names]

# Get the features' importance and their corresponding label
extraced_varimp = my_model.varimp(use_pandas=True)
df_feature_importances = pd.DataFrame(extraced_varimp[["scaled_importance", "variable"]])


# ------------------------------------------------- #
# -------------------- NAV BAR -------------------- #
# ------------------------------------------------- #
ODT_LOGO = "/assets/ODT_calc_icon.svg"

search_bar = dbc.Row(
    [
        dbc.Col(dbc.Input(type="search", placeholder="Search", id="search_bar")),
        dbc.Col(
            dbc.Button("Search", color="light", className="ml-2", id="search_bar_button"),
            width="auto",
        ),
    ],
    style={"margin-right": "3rem"},
    no_gutters=True,
    className="ml-auto flex-nowrap mt-3 mt-md-0",
    align="center",
)

navbar = dbc.Navbar(
    [
        html.A(
            # Use row and col to control vertical alignment of logo / brand
            dbc.Row(
                [
                    dbc.Col(html.Img(src=ODT_LOGO, height="30px")),
                    dbc.Col(html.P()),
                    dbc.Col(dbc.NavbarBrand("ODT calculator", className="ml-2")),
                ], style={"margin-left": "11%"},
                align="center",
                no_gutters=True,
            ),
            href="https://www.uj-cm.krakow.edu.pl",
        ),
        dbc.NavbarToggler(id="navbar-toggler"),
        dbc.Collapse(search_bar, id="navbar-collapse", navbar=True),
    ],
    color='primary',
    sticky="top",
    style={'width': 'calc(100% - 12rem)', 'float': 'right', 'height': '4.5rem'}
)

# ------------------------------------------------- #
# -------------------- SIDEBAR -------------------- #
# ------------------------------------------------- #


SIDEBAR_STYLE = {
    "position": "fixed",
    "top": 0,
    "left": 0,
    "bottom": 0,
    "width": "12rem",
    "padding": "1rem 1rem",
    "background-color": "#f8f9fa",
    'text-align': 'center'
}

links = {
    "Single prediction": ["/single-prediction", "single-prediction-link"],
    "Batch mode": ["/batch-mode", "batch-mode-link"]
}

sidebar = html.Div(
    [
        html.H6("Menu", className="display-4"),
        html.Hr(),
        dbc.Nav(
            [dbc.NavLink(x, href=links[x][0], id=links[x][1]) for x in links.keys()],
            vertical=True,
            pills=True
        ),
    ],
    style=SIDEBAR_STYLE,
)


# ----------------------------------------------- #
# ----------------- CONTENT STYLE --------------- #
# ----------------------------------------------- #
# CSS styling for main-page contents (user page and transaction page)
CONTENT_STYLE = {
    "margin-left": "13rem",
    "margin-right": "2rem",
    "padding": "2rem 1rem",
}




# ----------------------------------------------- #
# ------------- SINGLE PAGE --------------------- #
# ----------------------------------------------- #

# Initial data for single prediction page
# We create a Features Importance Bar Chart
fig_features_importance = go.Figure()
fig_features_importance.add_trace(go.Bar(x=df_feature_importances["variable"],
                                         y=df_feature_importances["scaled_importance"],
                                         marker_color='rgb(171,226,251)')
                                  )
fig_features_importance.update_layout(title_text='<b>Features Importance of the model<b>', title_x=0.5)

# We record the name, min, mean and max of the three most important features
sliders_label = my_data.columns
sliders_min = np.floor(my_data.min())
sliders_mean = np.floor(my_data.mean())
sliders_max = np.floor(my_data.max())


# Layout for user info page
# Page wrapped in dcc.Loading widget to add a loading animation when the page is loaded/updated
single_page = dcc.Loading(
                   children=html.Div([
                           # Title display
                           dbc.Row([dbc.Col(html.Div(html.H2(children="ODT Simulation Tool")))],
                                   style={"height": "40px", "width": "100%", "margin-left": "auto", "margin-right": "auto", "margin-bottom": "5px", "margin-top": "5px"}),

                           # Dash Graph Component calls the fig_features_importance parameters
                           # We display the most important feature's name
                           dcc.Graph(figure=fig_features_importance),

                           html.Hr(style={'size': '100%', 'color': 'grey'}),
                           html.Div(
                            [

                               dbc.Row(                                         # First row
                                            [
                                                dbc.Col(html.Div([
                                                    html.P(
                                                        sliders_label[0],
                                                        style={'width': '100%', 'align': 'left'}
                                                    ),
                                                    dbc.Row(
                                                        [
                                                            # The Dash Slider is built according to Feature #1 ranges
                                                            html.Div(
                                                                [
                                                                    dcc.Slider(id='X1_slider', min=sliders_min[0],
                                                                               max=sliders_max[0], step=0.1,
                                                                               value=sliders_mean[0],
                                                                               )
                                                                ],
                                                                style={'width': '70%', 'justify-content': 'left',
                                                                       'align-items': 'left'}
                                                            ),

                                                            dcc.Input(
                                                                id='X1_slider_value',
                                                                type='number',
                                                                min=sliders_min[0],
                                                                max=sliders_max[0],
                                                                value=sliders_mean[0],
                                                                style={'width': '20%', 'align': 'right'}
                                                            ),
                                                        ],
                                                    ),
                                                    html.Hr(style={'size': '33%', 'color': 'grey'}),
                                                    ]),
                                                    width={"size": 4, "order": 1},
                                                ),
                                                dbc.Col(
                                                    html.Div("The second of three columns"),
                                                    width={"size": 4, "order": 2},
                                                ),
                                                dbc.Col(
                                                    html.Div("The third of three columns"),
                                                    width={"size": 4, "order": 3},
                                                ),
                                            ]
                                        ),
                               dbc.Row(                                         # Second row
                                    [
                                        dbc.Col(
                                            html.Div("The first of three columns"),
                                            width={"size": 4, "order": 1},
                                        ),
                                        dbc.Col(
                                            html.Div("The second of three columns"),
                                            width={"size": 4, "order": 2},
                                        ),
                                        dbc.Col(
                                            html.Div("The third of three columns"),
                                            width={"size": 4, "order": 3},
                                        ),
                                    ]
                                ),

                               dbc.Row(                                         # Third row
                                    [
                                        dbc.Col(
                                            html.Div("The first of three columns"),
                                            width={"size": 4, "order": 1},
                                        ),
                                        dbc.Col(
                                            html.Div("The second of three columns"),
                                            width={"size": 4, "order": 2},
                                        ),
                                        dbc.Col(
                                            html.Div("The third of three columns"),
                                            width={"size": 4, "order": 3},
                                        ),
                                    ]
                                ),

                               dbc.Row(                                         # Fourth row
                                    [
                                        dbc.Col(
                                            html.Div("The first of three columns"),
                                            width={"size": 4, "order": 1},
                                        ),
                                        dbc.Col(
                                            html.Div("The second of three columns"),
                                            width={"size": 4, "order": 2},
                                        ),
                                        dbc.Col(
                                            html.Div("The third of three columns"),
                                            width={"size": 4, "order": 3},
                                        ),
                                    ]
                                ),

                               dbc.Row(                                         # Fifth row
                                    [
                                        dbc.Col(
                                            html.Div("The first of three columns"),
                                            width={"size": 4, "order": 1},
                                        ),
                                        dbc.Col(
                                            html.Div("The second of three columns"),
                                            width={"size": 4, "order": 2},
                                        ),
                                        dbc.Col(
                                            html.Div("The third of three columns"),
                                            width={"size": 4, "order": 3},
                                        ),
                                    ]
                                ),

                               dbc.Row(                                          # Sixth row
                                    [
                                        dbc.Col(
                                            html.Div("The first of three columns"),
                                            width={"size": 4, "order": 1},
                                        ),
                                        dbc.Col(
                                            html.Div("The second of three columns"),
                                            width={"size": 4, "order": 2},
                                        ),
                                        dbc.Col(
                                            html.Div("The third of three columns"),
                                            width={"size": 4, "order": 3},
                                        ),
                                    ]
                                ),

                               dbc.Row(                                            # Seventh row
                                    [
                                        dbc.Col(
                                            html.Div("The first of three columns"),
                                            width={"size": 4, "order": 1},
                                        ),
                                        dbc.Col(
                                            html.Div("The second of three columns"),
                                            width={"size": 4, "order": 2},
                                        ),
                                        dbc.Col(
                                            html.Div("The third of three columns"),
                                            width={"size": 4, "order": 3},
                                        ),
                                    ]
                                ),

                               dbc.Row(                                             # Eighth row
                                    [
                                        dbc.Col(
                                            html.Div("The first of three columns"),
                                            width={"size": 4, "order": 1},
                                        ),
                                        dbc.Col(
                                            html.Div("The second of three columns"),
                                            width={"size": 4, "order": 2},
                                        ),
                                        dbc.Col(
                                            html.Div("The third of three columns"),
                                            width={"size": 4, "order": 3},
                                        ),
                                    ]
                                ),

                               dbc.Row(                                             # Ninth row
                                    [
                                        dbc.Col(
                                            html.Div("The first of three columns"),
                                            width={"size": 4, "order": 1},
                                        ),
                                        dbc.Col(
                                            html.Div("The second of three columns"),
                                            width={"size": 4, "order": 2},
                                        ),
                                        dbc.Col(
                                            html.Div("The third of three columns"),
                                            width={"size": 4, "order": 3},
                                        ),
                                    ]
                                ),

                               dbc.Row(                                             # Tenth row
                                    [
                                        dbc.Col(
                                            html.Div("The first of three columns"),
                                            width={"size": 4, "order": 1},
                                        ),
                                        dbc.Col(
                                            html.Div("The second of three columns"),
                                            width={"size": 4, "order": 2},
                                        ),
                                        dbc.Col(
                                            html.Div("The third of three columns"),
                                            width={"size": 4, "order": 3},
                                        ),
                                    ]
                                ),
                            ]),

                           html.Div([
                               dbc.Row([


                                       html.P(
                                           sliders_label[1],
                                           style={'width': '100%', 'align': 'left'}
                                        ),

                                       html.Div([
                                           dbc.Col(
                                            [
                                                # The Dash Slider is built according to Feature #2 ranges
                                                html.Div(
                                                    [
                                                        dcc.Slider(id='X2_slider', min=sliders_min[1],
                                                                   max=sliders_max[1], step=0.1,
                                                                   value=sliders_mean[1],
                                                                   )
                                                    ],
                                                    style={'width': '80%', 'justify-content': 'center', 'align-items': 'center'}
                                                ),

                                                dcc.Input(
                                                    id='X2_slider_value',
                                                    type='number',
                                                    min=sliders_min[1],
                                                    max=sliders_max[1],
                                                    value=sliders_mean[1],
                                                    style={'width': '20%', 'align': 'right'}
                                                ),

                                            ]
                                           )
                                       ]),

                                       html.Hr(style={'size': '15%', 'color' : 'grey'}),

                                       html.P(
                                               sliders_label[2],
                                               style={'width': '100%', 'align': 'left'}
                                           ),
                                       html.Div([
                                           dbc.Col(
                                               [
                                                   # The Dash Slider is built according to Feature #3 ranges
                                                   html.Div(
                                                       [
                                                           dcc.Slider(id='X3_slider', min=sliders_min[2],
                                                                      max=sliders_max[2], step=0.1,
                                                                      value=sliders_mean[2],
                                                                      )
                                                       ],
                                                       style={'width': '80%', 'justify-content': 'center',
                                                              'align-items': 'center'}
                                                   ),

                                                   dcc.Input(
                                                       id='X3_slider_value',
                                                       type='number',
                                                       min=sliders_min[2],
                                                       max=sliders_max[2],
                                                       value=sliders_mean[2],
                                                       style={'width': '20%', 'align': 'right'}
                                                   ),

                                               ], width={"size": 4, "order": 3},
                                           )
                                       ]),

                                       html.Hr(style={'size': '15%', 'color': 'grey'}),

                                       ],
                                    style={'width': '33%', 'display': 'inline-block', 'align': 'left'},
                                       ),
                               dbc.Row([
                                   dbc.Col([html.Div(html.P('my next col'))])

                               ],
                                   style={'width': '33%', 'display': 'inline-block', 'margin': 'center'},
                               )
                               ]),
                           html.Div([

                           ],
                            style={'width': '33%', 'display': 'inline-block', 'margin': 'center'},
                           ),
                           # The prediction result will be displayed and updated here
                           html.Div([
                                html.P(),
                                html.H3(id="prediction_result")
                           ],
                               style={'width': '100%', 'display': 'inline-block'},
                           ),

                            ], className='prediction_result'),
                   )


app = dash.Dash(__name__, external_stylesheets=[dbc.themes.CERULEAN])
app.config.suppress_callback_exceptions = True
app.layout = html.Div([
                        dcc.Location(id="url", refresh=False),
                        sidebar,
                        navbar,
                        html.Div(id='page-content', style=CONTENT_STYLE)
])

# ------------------------------------- #
# ------------- CALLBACKS ------------- #
# ------------------------------------- #


# Switch pathname for url
@app.callback(
    [Output(f"{links[id][1]}", "active") for id in links.keys()],
    [Input("url", "pathname")],
)
def toggle_active_links(pathname):
    if pathname == "/" or pathname == "//":
        # Treat page 1 as the homepage / index
        return True, False
    return [pathname == f"{links[id][0]}" for id in links.keys()]

# Set page for each pathname
@app.callback(
    Output("page-content", "children"),
    [Input("url", "pathname")]
)
def render_page_content(pathname):
    if pathname in ["/", "//", f"{links[list(links.keys())[0]][0]}"]:
        return single_page
    else:
        return batch_page
    return dbc.Jumbotron(
        [
            html.H1("404: Not found", className="text-danger"),
            html.Hr(),
            html.P(f"The pathname {pathname} was not recognised..."),
        ]
    )


# The callback function will provide one "Output" in the form of a string (=children)
@app.callback([
    Output(component_id="prediction_result", component_property="children"),
    Output(component_id="X1_slider", component_property="value"),
    Output(component_id="X2_slider", component_property="value"),
    Output(component_id="X3_slider", component_property="value"),
    Output(component_id='X1_slider_value', component_property='value'),
    Output(component_id='X2_slider_value', component_property='value'),
    Output(component_id='X3_slider_value', component_property='value')
],
    # The values corresponding to the three sliders are obtained by calling their id and value property
    [
        Input("X1_slider", "value"),
        Input("X2_slider", "value"),
        Input("X3_slider", "value"),
        Input('X1_slider_value', 'value'),
        Input('X2_slider_value', 'value'),
        Input('X3_slider_value', 'value')
    ])
# The input variable are set in the same order as the callback Inputs
def update_prediction(X1, X2, X3, X1_value, X2_value, X3_value):

    ctx = dash.callback_context
    trigger_id = ctx.triggered[0]["prop_id"].split(".")[0]

    if trigger_id == "X1_slider_value":
        X1 = X1_value
    else:
        X1

    if trigger_id == "X1_slider":
        X1_value = X1
    else:
        X1_value

    if trigger_id == "X2_slider_value":
        X2 = X2_value
    else:
        X2

    if trigger_id == "X2_slider":
        X2_value = X2
    else:
        X2_value

    if trigger_id == "X3_slider_value":
        X3 = X3_value
    else:
        X3

    if trigger_id == "X3_slider":
        X3_value = X3
    else:
        X3_value


    # We create a NumPy array in the form of the original features
    # ["Pressure","Viscosity","Particles_size", "Temperature","Inlet_flow", "Rotating_Speed","pH","Color_density"]
    # Except for the X1, X2 and X3, all other non-influencing parameters are set to their mean
    input_X = my_data.copy()
    input_X = input_X.iloc[[0]]
    input_X.loc[:, 'API_perc'] = X1
    input_X.loc[:, 'Mannitol_perc'] = X2
    input_X.loc[:, 'MCC_perc'] = X3

    input_X = pd.DataFrame(input_X)

    my_data_h2o = h2o.H2OFrame(input_X)

    # Prediction is calculated based on the input_X array
    prediction = my_model.predict(my_data_h2o)
    prediction = prediction.as_data_frame()
    prediction = float(prediction.iloc[0])



    # And retuned to the Output of the callback function
    return [
            "Prediction: {}".format(round(prediction, 1)),
            X1,
            X2,
            X3,
            X1_value,
            X2_value,
            X3_value,
           ]




if __name__ == "__main__":
    app.run_server(host='0.0.0.0', port=8050, debug=True)
